Fix start-up order, only update in release (#674)
Since the failsafe_udpate start-up script needs to run `upgrade_tool`
(which accesses the FPGA), we need to run the script after the
initialization of the FPGA.

Release mode fixed SBP port device file rename

In release mode the device file for the fixed SBP port changes from
ttyGS2 to ttyGS2 despite our attempts to name it appropriately in the
usb gadget start-up script.

Helper commands to stream (or dump) syslog

Have S38usb_gadget use common.sh

Don't build everything twice, fix uboot deps

Also: Stage failsafe with post_image.sh

Use symlinks to find the correct device paths

Make sure upgrade files are cleared out

Remove unnecessary #define

diff --git a/board/piksiv3/rootfs-overlay/etc/init.d/S84_2_failsafe_update b/board/piksiv3/rootfs-overlay/etc/init.d/S84_2_failsafe_update
--- a/board/piksiv3/rootfs-overlay/etc/init.d/S84_2_failsafe_update
+++ b/board/piksiv3/rootfs-overlay/etc/init.d/S84_2_failsafe_update
@@ -1,5 +1,7 @@
 #!/bin/ash
 
+source /etc/init.d/common.sh
+
 name="failsafe_update"
 log_tag=$name
 
@@ -59,12 +61,23 @@ already_updated()
 
 run_upgrade_tool()
 {
+  /etc/init.d/S95watchdog_disable start
   upgrade_tool --debug --failsafe $staged_failsafe
 }
 
 do_failsafe_update()
 {
   logi "Checking failsafe bootloader..."
+
+  if ! lockdown; then
+    logi "Not a locked down image, do not need to upgrade failsafe..."
+    return 0
+  fi
+
+  if ! [[ -f "$staged_failsafe" ]]; then
+    loge --sbp "Error this is a locked down image, but there's no staged failsafe image..."
+    return 0
+  fi
 
   if already_updated; then
     logi "The failsafe bootloader is already up-to-date..."
