Wait for uart0/uart1 before loading the firmware

diff --git a/board/piksiv3/rootfs-overlay/etc/init.d/S85piksi_firmware b/board/piksiv3/rootfs-overlay/etc/init.d/S85piksi_firmware
--- a/board/piksiv3/rootfs-overlay/etc/init.d/S85piksi_firmware
+++ b/board/piksiv3/rootfs-overlay/etc/init.d/S85piksi_firmware
@@ -2,15 +2,35 @@
 
 name="piksi_firmware"
 
-start() {
+uart0_svc=/var/run/ports_daemon/sv/uart0/supervise/stat
+uart1_svc=/var/run/ports_daemon/sv/uart1/supervise/stat
+
+services_up()
+{
+  grep -q run $uart0_svc \
+    && grep -q run $uart1_svc
+}
+
+wait_services()
+{
+  while ! services_up; do
+    sleep 0.1;
+  done
+}
+
+start()
+{
+  wait_services
+
   if [ -f "/lib/firmware/piksi_firmware.elf" ]; then
-      modprobe zynq_remoteproc
+    modprobe zynq_remoteproc
   else
-      echo "ERROR: firmware not found"
+    echo "ERROR: firmware not found"
   fi
 }
 
-stop() {
+stop()
+{
   rmmod zynq_remoteproc
 }
 
