Merged pull 773 i On branch yi/DEVC-1053

diff --git a/board/piksiv3/rootfs-overlay/etc/init.d/S85piksi_firmware b/board/piksiv3/rootfs-overlay/etc/init.d/S85piksi_firmware
--- a/board/piksiv3/rootfs-overlay/etc/init.d/S85piksi_firmware
+++ b/board/piksiv3/rootfs-overlay/etc/init.d/S85piksi_firmware
@@ -1,10 +1,14 @@
 #!/bin/sh
 
 name="piksi_firmware"
+source /etc/init.d/common.sh
+ log_tag=$name # required by logging.sh
+source /etc/init.d/logging.sh
+ setup_loggers
 
 settings_ini=/persistent/config.ini
 
-uart_wait_count_limit=20 # wait 2s
+uart_wait_count_limit=2000 # wait 200s
 uart_check_interval=0.1
 
 
@@ -57,7 +61,7 @@ wait_services()
 
   while ! services_up; do
     if [[ $uart_wait_count -ge $uart_wait_count_limit ]]; then
-       echo "Timeout expired while waiting for UARTs" | sbp_log --err
+      loge --sbp "Timeout expired while waiting for UARTs"
       break;
     fi
      sleep $uart_check_interval
@@ -71,8 +75,9 @@ start()
 
   if [ -f "/lib/firmware/piksi_firmware.elf" ]; then
     modprobe zynq_remoteproc
+    logi "Remoteproc modprobe complete: $?"
   else
-    echo "ERROR: firmware not found"
+    loge "ERROR: firmware not found"
   fi
 }
 
